### ISSUE TITLE
Cron expressions with a list of days are not accepted by /addmultiple

### ISSUE THREAD

**Issue by averixus** [hsdevelops/cron-telebot#17]
When giving a list of jobs for `/addmultiple`, cron expressions with a list of days (such as `30 8 * * 2,4,5`) are ignored and not correctly added as jobs. If expressions with days lists are the only ones given, no jobs are added and the message `You know that's not right...` is returned.

I'm guessing the problem is something in the [regex for `extract_jobs`](https://github.com/hsdevelops/cron-telebot/blob/4534b2efc5bab8fddc171cb56005f06b772b1dfb/common/utils.py#L26) but I'm not confident enough to figure out what.

<img width="415" alt="Screenshot 2023-11-14 at 11 49 57" src="https://github.com/hsdevelops/cron-telebot/assets/9510882/cf59e3f7-ea9b-412b-a81f-9f1dbbec9efe">
<img width="414" alt="Screenshot 2023-11-14 at 11 50 35" src="https://github.com/hsdevelops/cron-telebot/assets/9510882/226b2c8d-6dd2-4731-af92-701e8348689f">

**Comment by huishun98** [comment]
Fixed 537319c9280c7083479ce502af5cf711a855a417
