### ISSUE TITLE
General Inquiry

### ISSUE THREAD

**Issue by yqlbu** [hsdevelops/cron-telebot#21]
## Summary

Hi,

Thanks for publishing an article about [How to Build and Deploy a python-telegram-bot v20 Webhook](https://www.freecodecamp.org/news/how-to-build-and-deploy-python-telegram-bot-v20-webhooks/). I am writing for an inquiry about the `push` (webhook) model that you mention in the post.

How could we make it possible to forward `ALL` message from a specific channel to the webhook we set up for the bot?

## Steps to reproduce

- Setup `smee webhook relay` to be able to receive messages from telegram
- Update `webhookUrl` for the bot
- Test

## Observation

![image](https://github.com/hsdevelops/cron-telebot/assets/31861128/b172b2ec-e115-4f17-b1c6-5377dd9c4ec8)

It seems that the webhook relay is ONLY able to receive messages that match the following format:

```shell
/xxxx@<bot-name>
```

## Inquiry

Any idea how to forward/push ALL messages to the designated webhook?

**Comment by huishun98** [comment]
I assume you're referring to groups? Because according to Telegram's [docs](https://core.telegram.org/bots/features#privacy-mode) all bots should receive all messages from channels where they are a member.

For groups, you will need to update the bot's [privacy mode](https://core.telegram.org/bots/features#privacy-mode) via [@BotFather](https://t.me/BotFather).

**Comment by yqlbu** [comment]
> I assume you're referring to groups? Because according to Telegram's [docs](https://core.telegram.org/bots/features#privacy-mode) all bots should receive all messages from channels where they are a member.
> 
> For groups, you will need to update the bot's [privacy mode](https://core.telegram.org/bots/features#privacy-mode) via [@BotFather](https://t.me/BotFather).

Thanks for your kind notes. Yup - the `privacy mode` indeed plays an important role in deciding if the bot can receive ALL messages. By default, the privacy mode is enabled.

Reference: https://core.telegram.org/bots/faq#what-messages-will-my-bot-get

**Comment by yqlbu** [comment]
Thanks your kind help!
